databases:
  - name: finances
    databaseName: finances_6xhs
    user: finances_6xhs_user

services:
  - type: web
    name: ndikumana
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finances
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false